Models/Manager/DashboardViewModel.cs
using SakeFigureShop.Domains;

namespace SakeFigureShop.Models.Manager
{
    public class DashboardViewModel
    {
        public double TotalRevenue;
        public long TotalOrders;
        public long TotalUser;
        public long TotalUnconfirmOrders;
        public long TotalProducts;
        public long TotalAnimes;
        public long TotalBrands;

        public IEnumerable<Order> ListUnconfirmOrders { get; set; } = new List<Order>();
        public IEnumerable<Order> ListConfirmedOrders { get; set; } = new List<Order>();
    }
}

Controllers/BrandsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SakeFigureShop.Data;
using SakeFigureShop.Domains;

namespace SakeFigureShop.Controllers
{
    public class BrandsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAuthorizationHandler _authService;
        private readonly UserManager<User> _userManager;
        private static string Message = string.Empty;


        public BrandsController(
            ApplicationDbContext context,
            IAuthorizationHandler authService,
            UserManager<User> userManager)
        {
            _context = context;
            _authService = authService;
            _userManager = userManager;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            ViewData["Message"] = null;
            if (!string.IsNullOrEmpty(Message))
            {
                ViewData["Message"] = Message;
                Message = string.Empty;
            }
            return _context.Brands != null ?
                        View(await _context.Brands.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Brands'  is null.");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                _context.Add(brand);
                await _context.SaveChangesAsync();
                Message = "Thêm thành công hãng: " + brand.Name;
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.Brands == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands.FindAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name")] Brand brand)
        {
            if (id != brand.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brand);
                    await _context.SaveChangesAsync();
                    Message = "Sửa thành công hãng: " + brand.Name;
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.Brands == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.Brands == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Brands'  is null.");
            }
            var brand = await _context.Brands.FindAsync(id);
            if (brand != null)
            {
                _context.Brands.Remove(brand);
            }

            Message = "Xóa thành công hãng: " + brand?.Name;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrandExists(long id)
        {
            return (_context.Brands?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SakeFigureShop.Data;
using SakeFigureShop.Domains;

namespace SakeFigureShop.Controllers
{
    public class FilmsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private static string Message = string.Empty;

        public FilmsController(ApplicationDbContext context)
        {
            _context = context;
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            ViewData["Message"] = null;
            if (!string.IsNullOrEmpty(Message))
            {
                ViewData["Message"] = Message;
                Message = string.Empty;
            }
            return _context.Films != null ?
                        View(await _context.Films.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Films'  is null.");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Film film)
        {
            if (ModelState.IsValid)
            {
                _context.Add(film);
                await _context.SaveChangesAsync();
                Message = "Thêm thành công anime: " + film.Name;
                return RedirectToAction(nameof(Index));
            }
            return View(film);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.Films == null)
            {
                return NotFound();
            }

            var film = await _context.Films.FindAsync(id);
            if (film == null)
            {
                return NotFound();
            }
            return View(film);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name")] Film film)
        {
            if (id != film.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(film);
                    await _context.SaveChangesAsync();
                    Message = "Sửa thành công anime: " + film.Name;
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmExists(film.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(film);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.Films == null)
            {
                return NotFound();
            }

            var film = await _context.Films
                .FirstOrDefaultAsync(m => m.Id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.Films == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Films'  is null.");
            }
            var film = await _context.Films.FindAsync(id);
            if (film != null)
            {
                _context.Films.Remove(film);
            }
            Message = "Đã xóa thành công anime: " + film?.Name;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmExists(long id)
        {
            return (_context.Films?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/ManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SakeFigureShop.Data;
using SakeFigureShop.Domains;
using SakeFigureShop.Models.Manager;

namespace SakeFigureShop.Controllers
{
    public class ManagerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public ManagerController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var vm = new DashboardViewModel();

            var allOrders = _context.Orders.Include(o => o.OrderDetails)
                .ThenInclude(od => od.Product);
            var allProducts = _context.Products;
            var allBrands = _context.Brands;
            var allFilms = _context.Films;

            var totalOrders = allOrders.Count();
            var listUnconfirmOrders = allOrders.Where(o => o.status == StatusType.NotConfirmed).ToList();
            var totalUnconfirmOrders = listUnconfirmOrders.Count();
            var totalDeliveriedOrder = allOrders.Where(o => o.status == StatusType.Deliveried).ToList();
            var listConfirmedOrders = allOrders.Where(o => o.status != StatusType.NotConfirmed).ToList();

            double totalRevenue = 0;

            foreach (var item in totalDeliveriedOrder)
            {
                totalRevenue += item.OrderDetails.Sum(od => od.Quantity * od.Product.Price);
            }

            vm.TotalOrders = totalOrders;
            vm.TotalUnconfirmOrders = totalUnconfirmOrders;
            vm.TotalRevenue = totalRevenue;
            vm.TotalProducts = allProducts.Count();
            vm.TotalBrands = allBrands.Count();
            vm.TotalAnimes = allFilms.Count();
            vm.ListUnconfirmOrders = listUnconfirmOrders;
            vm.ListConfirmedOrders = listConfirmedOrders;
            return View(vm);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult OrderDetail(int id)
        {
            var o = _context.Orders.Include(o => o.OrderDetails)
                .ThenInclude(od => od.Product).Where(o => o.Id == id).FirstOrDefault();
            return View(o);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> ChangeStatusOrder(int orderId, string status)
        {
            StatusType statusType;
            var order = _context.Orders.Include(o => o.OrderDetails)
                .ThenInclude(od => od.Product).Where(o => o.Id == orderId).FirstOrDefault();
            if (order == null)
            {
                return BadRequest("Không tìm thấy đơn hàng.");
            }
            if (Enum.TryParse(status, out statusType))
            {
                order.status = statusType;
                _context.Update(order);
                await _context.SaveChangesAsync();
                ViewData["Message"] = "Thành công.";
                return View("OrderDetail", order);
            } else
            {
                return BadRequest();
            }
        }
    }
}

Views/Manager/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model SakeFigureShop.Models.Manager.DashboardViewModel
@{
    ViewData["Title"] = "Admin Dashboard";
}
<div class="container-fluid">

    <div class="d-sm-flex mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
    </div>

    <div class="row">

        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Tổng đơn hàng
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">@Model.TotalOrders</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-receipt fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Tổng doanh thu
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">@Model.TotalRevenue.ToString("C", System.Globalization.CultureInfo.GetCultureInfo("vi-VN"))</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                Đơn hàng chưa xử lý
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">@Model.TotalUnconfirmOrders</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Tổng sản phẩm đang có
                            </div>
                            <div class="h5 mb-3 font-weight-bold text-gray-800">@Model.TotalProducts</div>
                            <div>
                                <a class="btn btn-primary" asp-action="Index" asp-controller="Products">Xem chi tiết</a>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-box fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Tổng Anime
                            </div>
                            <div class="h5 mb-3 font-weight-bold text-gray-800">@Model.TotalAnimes</div>
                            <div>
                                <a class="btn btn-primary" asp-action="Index" asp-controller="Films">Xem chi tiết</a>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-film fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                Tổng hãng
                            </div>
                            <div class="h5 mb-3 font-weight-bold text-gray-800">@Model.TotalBrands</div>
                            <div>
                                <a class="btn btn-primary" asp-action="Index" asp-controller="Brands">Xem chi tiết</a>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-copyright fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Đơn hàng chưa xử lý</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="order-not-confirm" class="table">
                        <thead>
                            <tr>
                                <th scope="col">Mã đơn hàng</th>
                                <th scope="col">Họ tên người nhận</th>
                                <th scope="col">Số lượng món hàng</th>
                                <th scope="col">Trạng thái</th>
                                <th scope="col">Ngày đặt hàng</th>
                                <th scope="col">Tổng tiền</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var o in Model.ListUnconfirmOrders)
                            {
                                var total = o.OrderDetails.Sum(od => od.Quantity * od.Product.Price);
                                <tr>
                                    <th scope="row"><a asp-controller="Manager" asp-action="OrderDetail" asp-route-id="@o.Id">@o.Id</a></th>
                                    <td>@o.Fullname</td>
                                    <td>@o.OrderDetails.Count()</td>
                                    <td>@o.status</td>
                                    <td>@o.CreatedDate</td>
                                    <td>@total.ToString("C", System.Globalization.CultureInfo.GetCultureInfo("vi-VN"))</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Đơn hàng đã xử lý</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="order-confirmed" class="table">
                        <thead>
                            <tr>
                                <th scope="col">Mã đơn hàng</th>
                                <th scope="col">Họ tên người nhận</th>
                                <th scope="col">Số lượng món hàng</th>
                                <th scope="col">Trạng thái</th>
                                <th scope="col">Ngày đặt hàng</th>
                                <th scope="col">Tổng tiền</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var o in Model.ListConfirmedOrders)
                            {
                                var total = o.OrderDetails.Sum(od => od.Quantity * od.Product.Price);
                                <tr>
                                    <th scope="row"><a asp-controller="Manager" asp-action="OrderDetail" asp-route-id="@o.Id">@o.Id</a></th>
                                    <td>@o.Fullname</td>
                                    <td>@o.OrderDetails.Count()</td>
                                    <td>@o.status</td>
                                    <td>@o.CreatedDate</td>
                                    <td>@total.ToString("C", System.Globalization.CultureInfo.GetCultureInfo("vi-VN"))</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#order-confirmed').DataTable();
        $('#order-not-confirm').DataTable();
        $('.dataTables_length').addClass('bs-select');
    });
</script>

Views/Manager/OrderDetail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using SakeFigureShop.Domains
@model SakeFigureShop.Domains.Order
@{
    ViewData["Title"] = "Xem đơn hàng";
    double totalPaid = 0;
}
<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-10 col-xl-8">
            <div class="card" style="border-radius: 10px;">
                <div class="card-header px-4 py-5">
                    <h5 class="text-muted mb-0">Chi tiết đơn hàng!</h5>
                </div>
                <div class="card-body p-4">
                    @foreach (var item in Model.OrderDetails)
                    {
                        var total = item.Quantity * item.Product.Price;
                        totalPaid += total;
                        <div class="card shadow-0 border mb-4">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-2">
                                        <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                                            <img src="@item.Product.ThumbnailImageUrl"
                                                 class="w-100" />
                                            <a href="/Home/Detail/@item.Product.Id">
                                                <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-md-4 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0">@item.Product.Name</p>
                                    </div>
                                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0 small">Số lượng: <br /> @item.Quantity</p>
                                    </div>
                                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0 small">Đơn giá: <br /> @item.Product.Price.ToString("C", System.Globalization.CultureInfo.GetCultureInfo("vi-VN"))</p>
                                    </div>
                                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                        <p class="text-muted mb-0 small">@total.ToString("C", System.Globalization.CultureInfo.GetCultureInfo("vi-VN"))</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                    <div class="d-flex pt-2">
                        <p class="text-muted mb-0">Mã đơn hàng: @Model.Id</p>
                    </div>

                    <div class="d-flex justify-content-between pt-2">
                        <p class="text-muted mb-0">Tình trạng đơn hàng: <b>@Model.status</b></p>
                        <p class="text-muted mb-0">
                            <span class="fw-bold me-4">Đổi trạng thái</span> 
                            <form method="post" asp-controller="Manager" asp-action="ChangeStatusOrder">
                                <input hidden value="@Model.Id" name="orderId"/>
                                <select class="form-select-sm" name="status">
                                    <option value="@StatusType.NotConfirmed">@StatusType.NotConfirmed</option>
                                    <option value="@StatusType.Confirmed">@StatusType.Confirmed</option>
                                    <option value="@StatusType.OnDelivery">@StatusType.OnDelivery</option>
                                    <option value="@StatusType.Deliveried">@StatusType.Deliveried</option>
                                </select>
                                <button type="submit" class="btn btn-primary">Thay đổi</button>
                            </form>
                        </p>
                    </div>

                    <div class="d-flex">
                        <p class="text-muted mb-0">Ngày đặt hàng: @Model.CreatedDate</p>
                    </div>
                </div>
                <div class="card-footer border-0 px-4 py-5"
                     style="border-bottom-left-radius: 10px; border-bottom-right-radius: 10px; background-color: slategray">
                    <h5 class="d-flex align-items-center justify-content-end text-white text-uppercase mb-0">
                        Tổng tiền: <span class="h2 mb-0 ms-2">@totalPaid.ToString("C", System.Globalization.CultureInfo.GetCultureInfo("vi-VN"))</span>
                    </h5>
                </div>
            </div>
        </div>
    </div>
</div>

@if (ViewData["Message"] != null)
{
    <script>
        $(() => {
            $("#liveToast").removeClass("hide").addClass("show")
            $("#toast-content").html('@ViewData["Message"]')
            setTimeout(() => {
                $("#close-btn").click()
            }, 2000)
        })
    </script>
}